//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office.Communication.OfficeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://localhost/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://localhost/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Office.Communication.OfficeService.Department DepartmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Office.Communication.OfficeService.Department Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="OfficeService.OfficeServiceSoap")]
    public interface OfficeServiceSoap {
        
        // CODEGEN: Generating message contract since element name LoadFromDepartmentsDatabaseResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/LoadFromDepartmentsDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponse LoadFromDepartmentsDatabase(Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/LoadFromDepartmentsDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponse> LoadFromDepartmentsDatabaseAsync(Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MaxDepartment", ReplyAction="*")]
        int MaxDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MaxDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MaxDepartmentAsync();
        
        // CODEGEN: Generating message contract since element name department from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateDepartmentInDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponse UpdateDepartmentInDatabase(Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateDepartmentInDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponse> UpdateDepartmentInDatabaseAsync(Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest request);
        
        // CODEGEN: Generating message contract since element name department from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SaveDepartmentToDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.SaveDepartmentToDatabaseResponse SaveDepartmentToDatabase(Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SaveDepartmentToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.SaveDepartmentToDatabaseResponse> SaveDepartmentToDatabaseAsync(Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest request);
        
        // CODEGEN: Generating message contract since element name department from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteDepartmentFromDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponse DeleteDepartmentFromDatabase(Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteDepartmentFromDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponse> DeleteDepartmentFromDatabaseAsync(Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest request);
        
        // CODEGEN: Generating message contract since element name LoadFromEmployeesDatabaseResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/LoadFromEmployeesDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponse LoadFromEmployeesDatabase(Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/LoadFromEmployeesDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponse> LoadFromEmployeesDatabaseAsync(Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MaxEmployee", ReplyAction="*")]
        int MaxEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MaxEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MaxEmployeeAsync();
        
        // CODEGEN: Generating message contract since element name employee from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateEmployeeInDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponse UpdateEmployeeInDatabase(Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateEmployeeInDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponse> UpdateEmployeeInDatabaseAsync(Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SaveEmployeeToDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.SaveEmployeeToDatabaseResponse SaveEmployeeToDatabase(Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SaveEmployeeToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.SaveEmployeeToDatabaseResponse> SaveEmployeeToDatabaseAsync(Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteEmployeeFromDatabase", ReplyAction="*")]
        Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponse DeleteEmployeeFromDatabase(Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteEmployeeFromDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponse> DeleteEmployeeFromDatabaseAsync(Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadFromDepartmentsDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadFromDepartmentsDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequestBody Body;
        
        public LoadFromDepartmentsDatabaseRequest() {
        }
        
        public LoadFromDepartmentsDatabaseRequest(Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadFromDepartmentsDatabaseRequestBody {
        
        public LoadFromDepartmentsDatabaseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadFromDepartmentsDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadFromDepartmentsDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponseBody Body;
        
        public LoadFromDepartmentsDatabaseResponse() {
        }
        
        public LoadFromDepartmentsDatabaseResponse(Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class LoadFromDepartmentsDatabaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Department[] LoadFromDepartmentsDatabaseResult;
        
        public LoadFromDepartmentsDatabaseResponseBody() {
        }
        
        public LoadFromDepartmentsDatabaseResponseBody(Office.Communication.OfficeService.Department[] LoadFromDepartmentsDatabaseResult) {
            this.LoadFromDepartmentsDatabaseResult = LoadFromDepartmentsDatabaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDepartmentInDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDepartmentInDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequestBody Body;
        
        public UpdateDepartmentInDatabaseRequest() {
        }
        
        public UpdateDepartmentInDatabaseRequest(Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UpdateDepartmentInDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Department department;
        
        public UpdateDepartmentInDatabaseRequestBody() {
        }
        
        public UpdateDepartmentInDatabaseRequestBody(Office.Communication.OfficeService.Department department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDepartmentInDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDepartmentInDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponseBody Body;
        
        public UpdateDepartmentInDatabaseResponse() {
        }
        
        public UpdateDepartmentInDatabaseResponse(Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateDepartmentInDatabaseResponseBody {
        
        public UpdateDepartmentInDatabaseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDepartmentToDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDepartmentToDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.SaveDepartmentToDatabaseRequestBody Body;
        
        public SaveDepartmentToDatabaseRequest() {
        }
        
        public SaveDepartmentToDatabaseRequest(Office.Communication.OfficeService.SaveDepartmentToDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class SaveDepartmentToDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Department department;
        
        public SaveDepartmentToDatabaseRequestBody() {
        }
        
        public SaveDepartmentToDatabaseRequestBody(Office.Communication.OfficeService.Department department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDepartmentToDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDepartmentToDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.SaveDepartmentToDatabaseResponseBody Body;
        
        public SaveDepartmentToDatabaseResponse() {
        }
        
        public SaveDepartmentToDatabaseResponse(Office.Communication.OfficeService.SaveDepartmentToDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveDepartmentToDatabaseResponseBody {
        
        public SaveDepartmentToDatabaseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDepartmentFromDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDepartmentFromDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequestBody Body;
        
        public DeleteDepartmentFromDatabaseRequest() {
        }
        
        public DeleteDepartmentFromDatabaseRequest(Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class DeleteDepartmentFromDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Department department;
        
        public DeleteDepartmentFromDatabaseRequestBody() {
        }
        
        public DeleteDepartmentFromDatabaseRequestBody(Office.Communication.OfficeService.Department department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDepartmentFromDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDepartmentFromDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponseBody Body;
        
        public DeleteDepartmentFromDatabaseResponse() {
        }
        
        public DeleteDepartmentFromDatabaseResponse(Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteDepartmentFromDatabaseResponseBody {
        
        public DeleteDepartmentFromDatabaseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadFromEmployeesDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadFromEmployeesDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequestBody Body;
        
        public LoadFromEmployeesDatabaseRequest() {
        }
        
        public LoadFromEmployeesDatabaseRequest(Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadFromEmployeesDatabaseRequestBody {
        
        public LoadFromEmployeesDatabaseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadFromEmployeesDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadFromEmployeesDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponseBody Body;
        
        public LoadFromEmployeesDatabaseResponse() {
        }
        
        public LoadFromEmployeesDatabaseResponse(Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class LoadFromEmployeesDatabaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Employee[] LoadFromEmployeesDatabaseResult;
        
        public LoadFromEmployeesDatabaseResponseBody() {
        }
        
        public LoadFromEmployeesDatabaseResponseBody(Office.Communication.OfficeService.Employee[] LoadFromEmployeesDatabaseResult) {
            this.LoadFromEmployeesDatabaseResult = LoadFromEmployeesDatabaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeInDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeInDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequestBody Body;
        
        public UpdateEmployeeInDatabaseRequest() {
        }
        
        public UpdateEmployeeInDatabaseRequest(Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UpdateEmployeeInDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Employee employee;
        
        public UpdateEmployeeInDatabaseRequestBody() {
        }
        
        public UpdateEmployeeInDatabaseRequestBody(Office.Communication.OfficeService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeInDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeInDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponseBody Body;
        
        public UpdateEmployeeInDatabaseResponse() {
        }
        
        public UpdateEmployeeInDatabaseResponse(Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateEmployeeInDatabaseResponseBody {
        
        public UpdateEmployeeInDatabaseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmployeeToDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveEmployeeToDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.SaveEmployeeToDatabaseRequestBody Body;
        
        public SaveEmployeeToDatabaseRequest() {
        }
        
        public SaveEmployeeToDatabaseRequest(Office.Communication.OfficeService.SaveEmployeeToDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class SaveEmployeeToDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Employee employee;
        
        public SaveEmployeeToDatabaseRequestBody() {
        }
        
        public SaveEmployeeToDatabaseRequestBody(Office.Communication.OfficeService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmployeeToDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveEmployeeToDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.SaveEmployeeToDatabaseResponseBody Body;
        
        public SaveEmployeeToDatabaseResponse() {
        }
        
        public SaveEmployeeToDatabaseResponse(Office.Communication.OfficeService.SaveEmployeeToDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveEmployeeToDatabaseResponseBody {
        
        public SaveEmployeeToDatabaseResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeFromDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeFromDatabase", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequestBody Body;
        
        public DeleteEmployeeFromDatabaseRequest() {
        }
        
        public DeleteEmployeeFromDatabaseRequest(Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class DeleteEmployeeFromDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Office.Communication.OfficeService.Employee employee;
        
        public DeleteEmployeeFromDatabaseRequestBody() {
        }
        
        public DeleteEmployeeFromDatabaseRequestBody(Office.Communication.OfficeService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeFromDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeFromDatabaseResponse", Namespace="http://localhost/", Order=0)]
        public Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponseBody Body;
        
        public DeleteEmployeeFromDatabaseResponse() {
        }
        
        public DeleteEmployeeFromDatabaseResponse(Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteEmployeeFromDatabaseResponseBody {
        
        public DeleteEmployeeFromDatabaseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OfficeServiceSoapChannel : Office.Communication.OfficeService.OfficeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfficeServiceSoapClient : System.ServiceModel.ClientBase<Office.Communication.OfficeService.OfficeServiceSoap>, Office.Communication.OfficeService.OfficeServiceSoap {
        
        public OfficeServiceSoapClient() {
        }
        
        public OfficeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfficeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfficeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.LoadFromDepartmentsDatabase(Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest request) {
            return base.Channel.LoadFromDepartmentsDatabase(request);
        }
        
        public Office.Communication.OfficeService.Department[] LoadFromDepartmentsDatabase() {
            Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest inValue = new Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequestBody();
            Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).LoadFromDepartmentsDatabase(inValue);
            return retVal.Body.LoadFromDepartmentsDatabaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.LoadFromDepartmentsDatabaseAsync(Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest request) {
            return base.Channel.LoadFromDepartmentsDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.LoadFromDepartmentsDatabaseResponse> LoadFromDepartmentsDatabaseAsync() {
            Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest inValue = new Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.LoadFromDepartmentsDatabaseRequestBody();
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).LoadFromDepartmentsDatabaseAsync(inValue);
        }
        
        public int MaxDepartment() {
            return base.Channel.MaxDepartment();
        }
        
        public System.Threading.Tasks.Task<int> MaxDepartmentAsync() {
            return base.Channel.MaxDepartmentAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.UpdateDepartmentInDatabase(Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest request) {
            return base.Channel.UpdateDepartmentInDatabase(request);
        }
        
        public void UpdateDepartmentInDatabase(Office.Communication.OfficeService.Department department) {
            Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest inValue = new Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequestBody();
            inValue.Body.department = department;
            Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).UpdateDepartmentInDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.UpdateDepartmentInDatabaseAsync(Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest request) {
            return base.Channel.UpdateDepartmentInDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.UpdateDepartmentInDatabaseResponse> UpdateDepartmentInDatabaseAsync(Office.Communication.OfficeService.Department department) {
            Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest inValue = new Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.UpdateDepartmentInDatabaseRequestBody();
            inValue.Body.department = department;
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).UpdateDepartmentInDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.SaveDepartmentToDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.SaveDepartmentToDatabase(Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest request) {
            return base.Channel.SaveDepartmentToDatabase(request);
        }
        
        public void SaveDepartmentToDatabase(Office.Communication.OfficeService.Department department) {
            Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest inValue = new Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.SaveDepartmentToDatabaseRequestBody();
            inValue.Body.department = department;
            Office.Communication.OfficeService.SaveDepartmentToDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).SaveDepartmentToDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.SaveDepartmentToDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.SaveDepartmentToDatabaseAsync(Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest request) {
            return base.Channel.SaveDepartmentToDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.SaveDepartmentToDatabaseResponse> SaveDepartmentToDatabaseAsync(Office.Communication.OfficeService.Department department) {
            Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest inValue = new Office.Communication.OfficeService.SaveDepartmentToDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.SaveDepartmentToDatabaseRequestBody();
            inValue.Body.department = department;
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).SaveDepartmentToDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.DeleteDepartmentFromDatabase(Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest request) {
            return base.Channel.DeleteDepartmentFromDatabase(request);
        }
        
        public void DeleteDepartmentFromDatabase(Office.Communication.OfficeService.Department department) {
            Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest inValue = new Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequestBody();
            inValue.Body.department = department;
            Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).DeleteDepartmentFromDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.DeleteDepartmentFromDatabaseAsync(Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest request) {
            return base.Channel.DeleteDepartmentFromDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.DeleteDepartmentFromDatabaseResponse> DeleteDepartmentFromDatabaseAsync(Office.Communication.OfficeService.Department department) {
            Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest inValue = new Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.DeleteDepartmentFromDatabaseRequestBody();
            inValue.Body.department = department;
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).DeleteDepartmentFromDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.LoadFromEmployeesDatabase(Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest request) {
            return base.Channel.LoadFromEmployeesDatabase(request);
        }
        
        public Office.Communication.OfficeService.Employee[] LoadFromEmployeesDatabase() {
            Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest inValue = new Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequestBody();
            Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).LoadFromEmployeesDatabase(inValue);
            return retVal.Body.LoadFromEmployeesDatabaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.LoadFromEmployeesDatabaseAsync(Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest request) {
            return base.Channel.LoadFromEmployeesDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.LoadFromEmployeesDatabaseResponse> LoadFromEmployeesDatabaseAsync() {
            Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest inValue = new Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.LoadFromEmployeesDatabaseRequestBody();
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).LoadFromEmployeesDatabaseAsync(inValue);
        }
        
        public int MaxEmployee() {
            return base.Channel.MaxEmployee();
        }
        
        public System.Threading.Tasks.Task<int> MaxEmployeeAsync() {
            return base.Channel.MaxEmployeeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.UpdateEmployeeInDatabase(Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest request) {
            return base.Channel.UpdateEmployeeInDatabase(request);
        }
        
        public void UpdateEmployeeInDatabase(Office.Communication.OfficeService.Employee employee) {
            Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest inValue = new Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequestBody();
            inValue.Body.employee = employee;
            Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).UpdateEmployeeInDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.UpdateEmployeeInDatabaseAsync(Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest request) {
            return base.Channel.UpdateEmployeeInDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.UpdateEmployeeInDatabaseResponse> UpdateEmployeeInDatabaseAsync(Office.Communication.OfficeService.Employee employee) {
            Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest inValue = new Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.UpdateEmployeeInDatabaseRequestBody();
            inValue.Body.employee = employee;
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).UpdateEmployeeInDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.SaveEmployeeToDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.SaveEmployeeToDatabase(Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest request) {
            return base.Channel.SaveEmployeeToDatabase(request);
        }
        
        public void SaveEmployeeToDatabase(Office.Communication.OfficeService.Employee employee) {
            Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest inValue = new Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.SaveEmployeeToDatabaseRequestBody();
            inValue.Body.employee = employee;
            Office.Communication.OfficeService.SaveEmployeeToDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).SaveEmployeeToDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.SaveEmployeeToDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.SaveEmployeeToDatabaseAsync(Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest request) {
            return base.Channel.SaveEmployeeToDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.SaveEmployeeToDatabaseResponse> SaveEmployeeToDatabaseAsync(Office.Communication.OfficeService.Employee employee) {
            Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest inValue = new Office.Communication.OfficeService.SaveEmployeeToDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.SaveEmployeeToDatabaseRequestBody();
            inValue.Body.employee = employee;
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).SaveEmployeeToDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponse Office.Communication.OfficeService.OfficeServiceSoap.DeleteEmployeeFromDatabase(Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest request) {
            return base.Channel.DeleteEmployeeFromDatabase(request);
        }
        
        public void DeleteEmployeeFromDatabase(Office.Communication.OfficeService.Employee employee) {
            Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest inValue = new Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequestBody();
            inValue.Body.employee = employee;
            Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponse retVal = ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).DeleteEmployeeFromDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponse> Office.Communication.OfficeService.OfficeServiceSoap.DeleteEmployeeFromDatabaseAsync(Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest request) {
            return base.Channel.DeleteEmployeeFromDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Office.Communication.OfficeService.DeleteEmployeeFromDatabaseResponse> DeleteEmployeeFromDatabaseAsync(Office.Communication.OfficeService.Employee employee) {
            Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest inValue = new Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequest();
            inValue.Body = new Office.Communication.OfficeService.DeleteEmployeeFromDatabaseRequestBody();
            inValue.Body.employee = employee;
            return ((Office.Communication.OfficeService.OfficeServiceSoap)(this)).DeleteEmployeeFromDatabaseAsync(inValue);
        }
    }
}
